### PR TITLE
Reduce git repo size by cleaning up *.mmdb commits

### PR DESCRIPTION
**Pull request by ALMaclaine**
The repo size was 79mb so I cleaned it up, now its ~100kbs

I ran this tool on the repo:

https://rtyley.github.io/bfg-repo-cleaner/

Here's my console output, it shows the deleted files mid-way through:

```bash
Alessandros-Mac-Pro:Desktop Diatta$ git clone --mirror https://github.com/ALMaclaine/node-geolite2.git
Cloning into bare repository 'node-geolite2.git'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 242 (delta 22), reused 41 (delta 20), pack-reused 190
Receiving objects: 100% (242/242), 75.44 MiB | 14.60 MiB/s, done.
Resolving deltas: 100% (108/108), done.
Alessandros-Mac-Pro:Desktop Diatta$ java -jar bfg-1.13.0.jar --delete-files *.mmdb node-geolite2/

Using repo : /Users/Diatta/Desktop/node-geolite2.git

Found 13 objects to protect
Found 7 tag-pointing refs : refs/tags/v1.1.0, refs/tags/v1.2.0, refs/tags/v1.2.1, ...
Found 8 commit-pointing refs : HEAD, refs/heads/key-file, refs/heads/key-sources, ...

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit 5927e3d7 (protected by 'HEAD')

Cleaning
--------

Found 70 commits
Cleaning commits:       100% (70/70)
Cleaning commits completed in 298 ms.

Updating 14 Refs
----------------

	Ref                       Before     After   
	---------------------------------------------
	refs/heads/key-file     | bf5c6635 | ad1b2dd1
	refs/heads/key-sources  | 2de90b7d | 8e8a9f6e
	refs/heads/master       | 5927e3d7 | fc7d5ca5
	refs/heads/mod-lfs      | dc4d074d | 856c2708
	refs/heads/runk-patch-1 | 6c450634 | 80300272
	refs/tags/v1.1.0        | 9fb5dfd5 | 21b5fb09
	refs/tags/v1.2.0        | 3f87614b | b9188692
	refs/tags/v1.2.1        | 7c9ecb66 | bc8bf54b
	refs/tags/v2.0.0        | ed1bec6a | dd179c8e
	refs/tags/v2.0.1        | 0acf8158 | ff1a5ddc
	refs/tags/v2.0.2        | a698ec83 | c5ff23a7
	refs/tags/v3.0.0        | f25cae8c | f02f0207
	refs/tags/v3.1.0        | 16b6bc6d | d19d2c16
	refs/tags/v3.2.0        | 7803435b | 12b2de05

Updating references:    100% (14/14)
...Ref update completed in 36 ms.

Commit Tree-Dirt History
------------------------

	Earliest                                              Latest
	|                                                          |
	.DDDDDDDDDDDDDDDDDDDDDmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

	D = dirty commits (file tree fixed)
	m = modified commits (commit message or parents changed)
	. = clean commits (no changes to file tree)

	                        Before     After   
	-------------------------------------------
	First modified commit | a328474f | 9b229f33
	Last dirty commit     | cd5b10d2 | bc6fae58

Deleted files
-------------

	Filename                Git id                                
	--------------------------------------------------------------
	GeoLite2-ASN.mmdb     | 42a917e9 (5.7 MB)                     
	GeoLite2-City.mmdb    | 50635e32 (72.6 MB), d2ee76f2 (60.8 MB)
	GeoLite2-Country.mmdb | 0c90fc15 (3.2 MB), 3168acaf (18.4 MB) 


In total, 98 object ids were changed. Full details are logged here:

	/Users/Diatta/Desktop/node-geolite2.git.bfg-report/2020-09-03/18-10-04

BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive

Alessandros-Mac-Pro:Desktop Diatta$ cd node-geolite2.git
Alessandros-Mac-Pro:node-geolite2.git Diatta$ git reflog expire --expire=now --all && git gc --prune=now --aggressive
Enumerating objects: 235, done.
Counting objects: 100% (235/235), done.
Delta compression using up to 12 threads
Compressing objects: 100% (226/226), done.
Writing objects: 100% (235/235), done.
Building bitmaps: 100% (70/70), done.
Total 235 (delta 121), reused 43 (delta 0)
Computing commit graph generation numbers: 100% (70/70), done.
Alessandros-Mac-Pro:node-geolite2.git Diatta$ git push
Enumerating objects: 235, done.
Writing objects: 100% (235/235), 75.38 KiB | 75.38 MiB/s, done.
Total 235 (delta 0), reused 0 (delta 0)
remote: Resolving deltas: 100% (121/121), done.
To https://github.com/ALMaclaine/node-geolite2.git
 + bf5c663...ad1b2dd key-file -> key-file (forced update)
 + 2de90b7...8e8a9f6 key-sources -> key-sources (forced update)
 + 5927e3d...fc7d5ca master -> master (forced update)
 + dc4d074...856c270 mod-lfs -> mod-lfs (forced update)
 + 6c45063...8030027 runk-patch-1 -> runk-patch-1 (forced update)
 + 9fb5dfd...21b5fb0 v1.1.0 -> v1.1.0 (forced update)
 + 3f87614...b918869 v1.2.0 -> v1.2.0 (forced update)
 + 7c9ecb6...bc8bf54 v1.2.1 -> v1.2.1 (forced update)
 + ed1bec6...dd179c8 v2.0.0 -> v2.0.0 (forced update)
 + 0acf815...ff1a5dd v2.0.1 -> v2.0.1 (forced update)
 + a698ec8...c5ff23a v2.0.2 -> v2.0.2 (forced update)
 + f25cae8...f02f020 v3.0.0 -> v3.0.0 (forced update)
 + 16b6bc6...d19d2c1 v3.1.0 -> v3.1.0 (forced update)
 + 7803435...12b2de0 v3.2.0 -> v3.2.0 (forced update)
```

Let me know if you're willing to accept this change and then I'll do the other PR regardless.

Thanks

### CODE REVIEW

**Comment by ALMaclaine** [comment]
I read the Travis logs and it's failing from a missing license key, is that something I'm supposed to do?

**Comment by runk** [comment]
Hey! Thanks for the PR. 

The diff looks quite weird - e.g. it shows changes to `.travis.yml` etc - do you know why?

**Comment by ALMaclaine** [comment]
Pretty sure it re-writes all the commits without the large files.

You can see at the top it consists of 65 commits, which is about how many commits the repo has right now.

I'm not sure if its going to tack them all on, giving ~130 commits or leave it with just ~65.

I spot checked several files and it all looks good.

Up to you whether you think it's a worth while trade off but I thought it seemed like a good idea since a perfect git history is of questionable value in a project this small.

Let me know what you think and if I should do anything.

**Comment by runk** [comment]
Okay, let's get it into master and I'll figure what's the deal with failing build

**Comment by runk** [comment]
Thanks for the contribution 🙇 

Not 100% sure what was the problem with the build, it's quite puzzling.

**Comment by ALMaclaine** [comment]
Awesome, I'll work on the next part now.

**Pull request merged**
